### ISSUE TITLE
kendra_retriever_samples/requirement.txt needs update

### ISSUE THREAD

**Issue by rovitini** [aws-samples/amazon-kendra-langchain-extensions#29]
Existing requirements.txt version refers to a wrong langchain version
----
- langchain==0.0.219  >>> does not exist
+langchain==0.0.21 
boto3>=1.26.159
openai
anthropic
streamlit
----
after updating langchain to 0.0.21, prompt suggest to use the pip 2020 feature resolver: 
 pip install -r requirements.txt --use-feature=2020-resolver
----
Resulted in : 
Successfully uninstalled pydantic-2.0.3
Successfully installed pydantic-1.10.12
----

**Comment by rovitini** [comment]
this error happened, when using cloud9.

**Comment by athewsey** [comment]
Hi, I can confirm [langchain==0.0.219 does exist](https://pypi.org/project/langchain/0.0.219/) and installs fine for me. I think the most likely cause of this is you need to upgrade your **Python** version? Per the link, v0.0.219 requires `Python >=3.8.1, <4.0`

I probably wouldn't recommend downloading to such an old version as [0.0.21](https://pypi.org/project/langchain/0.0.21/) - the library has changed quite a bit since then.

**Comment by MithilShah** [comment]
Upgraded to langchain 0.0.263
